// Generated by Tools/protocol_generator/generate.py. Do not edit.
#pragma once
#include <cstddef>
#include <cstdint>

namespace ch4::protocol {
inline constexpr std::uint8_t kSof0 = 0xA5;
inline constexpr std::uint8_t kSof1 = 0x5A;
inline constexpr std::uint8_t kVersion = 1;
inline constexpr std::uint16_t kUartMaxPayload = 1024;
inline constexpr std::uint16_t kUsbMaxPayload = 4080;
inline constexpr std::uint16_t kMaxPayload = 4080;
inline constexpr std::size_t kFrameOverhead = 13;
inline constexpr std::size_t kFusedPointSize = 48;

enum class Address : std::uint8_t {
    Host = 0x00,
    Fpga = 0x01,
    Broadcast = 0xFF,
};

enum class Flag : std::uint8_t {
    AckRequired = 1u << 0,
    IsResponse = 1u << 1,
    HasError = 1u << 2,
    MoreFragments = 1u << 3,
    FirstFragment = 1u << 4,
    LastFragment = 1u << 5,
    DataValid = 1u << 6,
};

enum class MessageType : std::uint8_t {
    Hello = 0x01,
    Heartbeat = 0x02,
    TimeQuery = 0x03,
    CapabilityQuery = 0x04,
    ReadReg = 0x10,
    WriteReg = 0x11,
    ReadBlock = 0x12,
    WriteBlock = 0x13,
    ValidateConfig = 0x20,
    CommitConfig = 0x21,
    LoadDefaultConfig = 0x22,
    StartScan = 0x30,
    StopScan = 0x31,
    StaticPoint = 0x32,
    ReturnZero = 0x33,
    ReturnScanStart = 0x34,
    StartAcquisition = 0x35,
    StopAcquisition = 0x36,
    StatusQuery = 0x40,
    ClearErrors = 0x41,
    StatsQuery = 0x42,
    StreamConfig = 0x50,
    StreamStart = 0x51,
    StreamStop = 0x52,
    ImageBegin = 0x60,
    LineEvent = 0x61,
    FusedPoint = 0x62,
    ImageEnd = 0x63,
    AngleSample = 0x70,
    HarmonicCurve = 0x71,
    RawSamples = 0x72,
};

enum class Status : std::uint8_t {
    Ok = 0x00,
    BadVersion = 0x01,
    BadCrc = 0x02,
    BadLength = 0x03,
    WrongAddress = 0x04,
    UnknownMessage = 0x05,
    InvalidRegister = 0x06,
    ReadOnly = 0x07,
    OutOfRange = 0x08,
    InvalidCombination = 0x09,
    DeviceBusy = 0x0A,
    InvalidState = 0x0B,
    NoData = 0x0C,
    BufferOverflow = 0x0D,
    ConfigNotCommitted = 0x0E,
    Unsupported = 0x0F,
    InternalError = 0x10,
};

enum class FusedPointFlag : std::uint16_t {
    XReverse = 1u << 0,
    Endpoint = 1u << 1,
    LineTransition = 1u << 2,
    FilterSettled = 1u << 3,
    AngleValid = 1u << 4,
    AngleInterpolated = 1u << 5,
    DilaValid = 1u << 6,
    A1AboveThreshold = 1u << 7,
    LowConfidence = 1u << 8,
    Overflow = 1u << 9,
};

}  // namespace ch4::protocol
