set_property PACKAGE_PIN W19 [get_ports Clk_50M_In]
set_property IOSTANDARD LVCMOS33 [get_ports Clk_50M_In]
create_clock -period 20.000 -name sys_clk [get_ports Clk_50M_In]
set_property PACKAGE_PIN B22 [get_ports Resetn]
set_property IOSTANDARD LVCMOS33 [get_ports Resetn]
set_property PACKAGE_PIN C19 [get_ports Bitstream_Done]
set_property PACKAGE_PIN U22 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports {Bitstream_Done led}]
set_property PACKAGE_PIN AA20 [get_ports HRACT]
set_property PACKAGE_PIN W11 [get_ports HRCLK]
set_property PACKAGE_PIN AA21 [get_ports HRVLD]
set_property PACKAGE_PIN U17 [get_ports HTACK]
set_property PACKAGE_PIN V13 [get_ports HTCLK]
set_property PACKAGE_PIN U16 [get_ports HTRDY]
set_property PACKAGE_PIN V17 [get_ports HTREQ]
set_property PACKAGE_PIN U18 [get_ports HTVLD]
set_property PACKAGE_PIN E19 [get_ports Rx_Ctrl]
set_property PACKAGE_PIN D19 [get_ports Tx_Ctrl]
set_property IOSTANDARD LVCMOS33 [get_ports {HRACT HRCLK HRVLD HTACK HTCLK HTRDY HTREQ HTVLD Rx_Ctrl Tx_Ctrl}]
set_property PACKAGE_PIN AA15 [get_ports {HD[0]}]
set_property PACKAGE_PIN AB15 [get_ports {HD[1]}]
set_property PACKAGE_PIN AB16 [get_ports {HD[2]}]
set_property PACKAGE_PIN AB17 [get_ports {HD[3]}]
set_property PACKAGE_PIN V10 [get_ports {HD[4]}]
set_property PACKAGE_PIN W10 [get_ports {HD[5]}]
set_property PACKAGE_PIN W12 [get_ports {HD[6]}]
set_property PACKAGE_PIN AA9 [get_ports {HD[7]}]
set_property PACKAGE_PIN AB10 [get_ports {HD[8]}]
set_property PACKAGE_PIN Y11 [get_ports {HD[9]}]
set_property PACKAGE_PIN Y12 [get_ports {HD[10]}]
set_property PACKAGE_PIN W15 [get_ports {HD[11]}]
set_property PACKAGE_PIN W16 [get_ports {HD[12]}]
set_property PACKAGE_PIN Y16 [get_ports {HD[13]}]
set_property PACKAGE_PIN AA16 [get_ports {HD[14]}]
set_property PACKAGE_PIN Y17 [get_ports {HD[15]}]
set_property PACKAGE_PIN AA10 [get_ports {HD[16]}]
set_property PACKAGE_PIN AA11 [get_ports {HD[17]}]
set_property PACKAGE_PIN AB11 [get_ports {HD[18]}]
set_property PACKAGE_PIN AB12 [get_ports {HD[19]}]
set_property PACKAGE_PIN AA13 [get_ports {HD[20]}]
set_property PACKAGE_PIN AB13 [get_ports {HD[21]}]
set_property PACKAGE_PIN Y13 [get_ports {HD[22]}]
set_property PACKAGE_PIN AA14 [get_ports {HD[23]}]
set_property PACKAGE_PIN W14 [get_ports {HD[24]}]
set_property PACKAGE_PIN Y14 [get_ports {HD[25]}]
set_property PACKAGE_PIN V14 [get_ports {HD[26]}]
set_property PACKAGE_PIN U15 [get_ports {HD[27]}]
set_property PACKAGE_PIN V15 [get_ports {HD[28]}]
set_property PACKAGE_PIN T14 [get_ports {HD[29]}]
set_property PACKAGE_PIN T15 [get_ports {HD[30]}]
set_property PACKAGE_PIN T16 [get_ports {HD[31]}]
set_property IOSTANDARD LVCMOS33 [get_ports {HD[*]}]
create_clock -period 8.330 -name hspi_rx_clk [get_ports HRCLK]
set hspi_tx_source [get_pins -quiet clk_wiz_0_inst/inst/mmcm_adv_inst/CLKOUT0]
if {[llength $hspi_tx_source] == 0} {set hspi_tx_source [get_pins -quiet mmcm/CLKOUT0]}
set hspi_tx_sink [get_pins -quiet tx_clk_30m_bufg/O]
if {[llength $hspi_tx_sink] == 0} {set hspi_tx_sink [get_pins -quiet tx_clk_30m_buf/O]}
if {[llength $hspi_tx_source] != 0 && [llength $hspi_tx_sink] != 0} {
 create_generated_clock -name hspi_tx_clk -source $hspi_tx_source -divide_by 4 $hspi_tx_sink
}
set_clock_groups -asynchronous -group [get_clocks hspi_rx_clk] -group [get_clocks -include_generated_clocks sys_clk]
set_property SLEW FAST [get_ports {HD[*] HTACK HTCLK HTREQ HTVLD}]
set_property DRIVE 16 [get_ports {HD[*] HTACK HTCLK HTREQ HTVLD}]
