#include "storage/session_recorder.h"
#include <QDateTime>
#include <QDir>
#include <QJsonDocument>
#include <QJsonObject>
namespace ch4::storage {
SessionRecorder::SessionRecorder(QObject*p):QObject(p){}
bool SessionRecorder::start(const QString& rootDirectory,const QString& mode){stop();const QString stamp=QDateTime::currentDateTime().toString(QStringLiteral("yyyyMMdd_HHmmss_zzz"));const QString root=rootDirectory.isEmpty()?QStringLiteral(CH4_PROJECT_ROOT "/Data"):rootDirectory;if(!QDir().mkpath(root))return false;directory_=QDir(root).filePath(QStringLiteral("session_%1").arg(stamp));if(!QDir().mkpath(directory_))return false;
 QFile meta(directory_+QStringLiteral("/session.json"));if(meta.open(QIODevice::WriteOnly)){QJsonObject o{{"mode",mode},{"started",QDateTime::currentDateTime().toString(Qt::ISODateWithMs)},{"signal_label","relative methane signal / simulated concentration"},{"protocol_version",1}};meta.write(QJsonDocument(o).toJson());}
 pointsFile_.setFileName(directory_+QStringLiteral("/fused_points.csv"));anglesFile_.setFileName(directory_+QStringLiteral("/angles.csv"));harmonicsFile_.setFileName(directory_+QStringLiteral("/harmonics.csv"));eventsFile_.setFileName(directory_+QStringLiteral("/events.csv"));if(!pointsFile_.open(QIODevice::WriteOnly|QIODevice::Text)||!anglesFile_.open(QIODevice::WriteOnly|QIODevice::Text)||!harmonicsFile_.open(QIODevice::WriteOnly|QIODevice::Text)||!eventsFile_.open(QIODevice::WriteOnly|QIODevice::Text)){stop();return false;}
 points_.setDevice(&pointsFile_);angles_.setDevice(&anglesFile_);harmonics_.setDevice(&harmonicsFile_);events_.setDevice(&eventsFile_);pendingRows_=0;points_<<"measurement_ticks,image_id,line_id,point_id,x_q13,y_q13,x_deg,y_deg,i1,q1,i2,q2,a1,a2,a2_over_a1,flags,config_revision\n";angles_<<"measurement_ticks,sample_index,x_q13,y_q13,x_deg,y_deg\n";harmonics_<<"measurement_ticks,sample_index,i1,q1,i2,q2,a1,a2\n";events_<<"pc_time,event\n";event(QStringLiteral("session_start"));return true;}
void SessionRecorder::append(const model::FusedPoint&p){if(!pointsFile_.isOpen())return;points_<<p.measurementTime<<','<<p.imageId<<','<<p.lineId<<','<<p.pointId<<','<<p.xAngleQ13<<','<<p.yAngleQ13<<','<<QString::number(p.xDegrees(),'f',6)<<','<<QString::number(p.yDegrees(),'f',6)<<','<<p.i1<<','<<p.q1<<','<<p.i2<<','<<p.q2<<','<<p.a1<<','<<p.a2<<','<<QString::number(p.ratio(),'g',12)<<','<<QString::number(p.flags,16)<<','<<p.configRevision<<'\n';if(++pendingRows_>=100){points_.flush();angles_.flush();harmonics_.flush();pendingRows_=0;}}
void SessionRecorder::append(const model::AngleSample&s){if(anglesFile_.isOpen())angles_<<s.measurementTime<<','<<s.sampleIndex<<','<<s.xAngleQ13<<','<<s.yAngleQ13<<','<<QString::number(s.xDegrees(),'f',6)<<','<<QString::number(s.yDegrees(),'f',6)<<'\n';}
void SessionRecorder::append(const model::HarmonicCurve&c){if(harmonicsFile_.isOpen())harmonics_<<c.measurementTime<<','<<c.sampleIndex<<','<<c.i1<<','<<c.q1<<','<<c.i2<<','<<c.q2<<','<<QString::number(c.amplitude1f(),'g',12)<<','<<QString::number(c.amplitude2f(),'g',12)<<'\n';}
void SessionRecorder::event(const QString&t){if(eventsFile_.isOpen()){events_<<QDateTime::currentDateTime().toString(Qt::ISODateWithMs)<<','<<t<<'\n';events_.flush();}}
void SessionRecorder::stop(){if(pointsFile_.isOpen()){event(QStringLiteral("session_stop"));points_.flush();angles_.flush();harmonics_.flush();events_.flush();pointsFile_.close();anglesFile_.close();harmonicsFile_.close();eventsFile_.close();}pendingRows_=0;points_.setDevice(nullptr);angles_.setDevice(nullptr);harmonics_.setDevice(nullptr);events_.setDevice(nullptr);}
}  // namespace ch4::storage
