#!/usr/bin/env python3
"""Generate protocol constants, reference documents, and fixed test frames.

The two .yaml files are intentionally written as JSON, which is valid YAML 1.2.
That keeps the generator dependency-free on clean Windows development machines.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import struct
import sys
from dataclasses import dataclass


ROOT = pathlib.Path(__file__).resolve().parents[2]
PROTOCOL_PATH = ROOT / "Shared" / "protocol.yaml"
REGISTER_PATH = ROOT / "Shared" / "register_map.yaml"


def load_definition(path: pathlib.Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{path.name} 不是本项目约定的 JSON-compatible YAML: {exc}") from exc


def crc16_ccitt_false(data: bytes, initial: int = 0xFFFF) -> int:
    crc = initial
    for value in data:
        crc ^= value << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def encode_frame(protocol: dict, *, dst: int, src: int, message_type: int,
                 flags: int, sequence: int, payload: bytes = b"") -> bytes:
    settings = protocol["protocol"]
    if len(payload) > settings["max_application_payload"]:
        raise ValueError("payload exceeds max_application_payload")
    body = struct.pack(
        "<BBBBBHH",
        settings["version"], dst, src, message_type, flags, sequence, len(payload)
    ) + payload
    return bytes(settings["sof"]) + body + struct.pack("<H", crc16_ccitt_false(body))


def validate(protocol: dict, register_map: dict) -> None:
    settings = protocol["protocol"]
    if settings["byte_order"] != "little":
        raise ValueError("stage 0 protocol must be little-endian")
    if settings["frame_overhead_bytes"] != 13 or settings["header_bytes_without_sof"] != 9:
        raise ValueError("frame header size is inconsistent with A5 5A + 9-byte body header + CRC16")
    if settings["uart_max_payload"] > settings["max_application_payload"]:
        raise ValueError("UART payload limit exceeds application limit")
    if settings["usb_max_payload"] + 16 > 4096:
        raise ValueError("USB payload does not leave room for the application frame")

    for group_name in ("flags", "message_types", "status_codes", "capabilities"):
        values = list(protocol[group_name].values())
        if len(values) != len(set(values)):
            raise ValueError(f"duplicate value in {group_name}")
    if any(bit < 0 or bit > 7 for bit in protocol["flags"].values()):
        raise ValueError("flag bits must be in [0, 7]")

    fields = protocol["fused_point"]["fields"]
    cursor = 0
    for field in fields:
        if field["offset"] != cursor:
            raise ValueError(f"fused point gap/overlap before {field['name']}")
        cursor += field["size"]
    if cursor != protocol["fused_point"]["size"] or cursor != 48:
        raise ValueError("fused point must remain exactly 48 bytes")

    registers = register_map["registers"]
    names = [reg["name"] for reg in registers]
    addresses = [reg["address"] for reg in registers]
    if len(names) != len(set(names)) or len(addresses) != len(set(addresses)):
        raise ValueError("register names and addresses must be unique")
    if any(address % 4 for address in addresses):
        raise ValueError("all 32-bit registers must be 4-byte aligned")
    valid_access = {"ro", "rw", "wo", "rw1c", "shadow"}
    if any(reg["access"] not in valid_access for reg in registers):
        raise ValueError("unsupported register access type")


def hex_u(value: int, width: int) -> str:
    return f"0x{value:0{width}X}"


def render_cpp_protocol(spec: dict) -> str:
    settings = spec["protocol"]
    lines = [
        "// Generated by Tools/protocol_generator/generate.py. Do not edit.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace ch4::protocol {",
        f"inline constexpr std::uint8_t kSof0 = {hex_u(settings['sof'][0], 2)};",
        f"inline constexpr std::uint8_t kSof1 = {hex_u(settings['sof'][1], 2)};",
        f"inline constexpr std::uint8_t kVersion = {settings['version']};",
        f"inline constexpr std::uint16_t kUartMaxPayload = {settings['uart_max_payload']};",
        f"inline constexpr std::uint16_t kUsbMaxPayload = {settings['usb_max_payload']};",
        f"inline constexpr std::uint16_t kMaxPayload = {settings['max_application_payload']};",
        f"inline constexpr std::size_t kFrameOverhead = {settings['frame_overhead_bytes']};",
        f"inline constexpr std::size_t kFusedPointSize = {spec['fused_point']['size']};",
        "",
        "enum class Address : std::uint8_t {",
    ]
    for name, value in spec["addresses"].items():
        lines.append(f"    {camel(name)} = {hex_u(value, 2)},")
    lines += ["};", "", "enum class Flag : std::uint8_t {"]
    for name, bit in spec["flags"].items():
        lines.append(f"    {camel(name)} = 1u << {bit},")
    lines += ["};", "", "enum class MessageType : std::uint8_t {"]
    for name, value in spec["message_types"].items():
        lines.append(f"    {camel(name)} = {hex_u(value, 2)},")
    lines += ["};", "", "enum class Status : std::uint8_t {"]
    for name, value in spec["status_codes"].items():
        lines.append(f"    {camel(name)} = {hex_u(value, 2)},")
    lines += ["};", "", "enum class FusedPointFlag : std::uint16_t {"]
    for name, bit in spec["fused_point_flags"].items():
        lines.append(f"    {camel(name)} = 1u << {bit},")
    lines += ["};", "", "}  // namespace ch4::protocol", ""]
    return "\n".join(lines)


def render_cpp_registers(spec: dict) -> str:
    lines = [
        "// Generated by Tools/protocol_generator/generate.py. Do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace ch4::registers {",
        "enum class Address : std::uint16_t {",
    ]
    for reg in spec["registers"]:
        lines.append(f"    {camel(reg['name'])} = {hex_u(reg['address'], 4)},")
    lines += ["};", "", "}  // namespace ch4::registers", ""]
    return "\n".join(lines)


def render_verilog(spec: dict, register_map: dict) -> str:
    settings = spec["protocol"]
    lines = [
        "// Generated by Tools/protocol_generator/generate.py. Do not edit.",
        "`ifndef CH4_PROTOCOL_DEFS_VH",
        "`define CH4_PROTOCOL_DEFS_VH",
        f"`define CH4_SOF0 8'h{settings['sof'][0]:02X}",
        f"`define CH4_SOF1 8'h{settings['sof'][1]:02X}",
        f"`define CH4_PROTOCOL_VERSION 8'h{settings['version']:02X}",
        f"`define CH4_MAX_PAYLOAD {settings['max_application_payload']}",
        f"`define CH4_UART_MAX_PAYLOAD {settings['uart_max_payload']}",
        f"`define CH4_USB_MAX_PAYLOAD {settings['usb_max_payload']}",
        f"`define CH4_FUSED_POINT_SIZE {spec['fused_point']['size']}",
        "",
    ]
    for name, bit in spec["flags"].items():
        lines.append(f"`define CH4_FLAG_{name} 8'h{1 << bit:02X}")
    lines.append("")
    for name, value in spec["message_types"].items():
        lines.append(f"`define CH4_MSG_{name} 8'h{value:02X}")
    lines.append("")
    for name, value in spec["status_codes"].items():
        lines.append(f"`define CH4_STATUS_{name} 8'h{value:02X}")
    lines.append("")
    for reg in register_map["registers"]:
        lines.append(f"`define CH4_REG_{reg['name']} 16'h{reg['address']:04X}")
    lines += ["", "`endif", ""]
    return "\n".join(lines)


def camel(name: str) -> str:
    return "".join(part.capitalize() for part in name.lower().split("_"))


def markdown_protocol(spec: dict) -> str:
    p = spec["protocol"]
    lines = [
        "# 统一通信协议",
        "",
        "> 本文档由 `Shared/protocol.yaml` 自动生成；请勿直接修改。",
        "",
        "## 固定规则",
        "",
        f"- 协议版本：{p['version']}；多字节字段：小端；硬件计时：50 MHz（每 tick 20 ns）。",
        "- 帧格式：`A5 5A | version | dst | src | type | flags | sequence:u16 | payload_length:u16 | payload | crc16:u16`。",
        f"- UART 载荷上限 {p['uart_max_payload']} 字节；USB 载荷上限 {p['usb_max_payload']} 字节。",
        "- CRC-16/CCITT-FALSE 覆盖 `version` 到 payload 最后一个字节，CRC 本身按小端发送。",
        "- 响应保持请求 type，设置 `IS_RESPONSE`，回显 sequence；payload 首字节为状态码。",
        "- 仅 UART 是第一版控制通道；USB 在阶段 2 作为主数据通道，不改变应用帧。",
        "",
        "## 标志位",
        "",
        "| 名称 | 位 | 掩码 |",
        "|---|---:|---:|",
    ]
    for name, bit in spec["flags"].items():
        lines.append(f"| `{name}` | {bit} | `0x{1 << bit:02X}` |")
    lines += ["", "## 消息类型", "", "| 名称 | 值 |", "|---|---:|"]
    for name, value in spec["message_types"].items():
        lines.append(f"| `{name}` | `0x{value:02X}` |")
    lines += ["", "## 状态码", "", "| 名称 | 值 |", "|---|---:|"]
    for name, value in spec["status_codes"].items():
        lines.append(f"| `{name}` | `0x{value:02X}` |")
    lines += [
        "", "## 48 字节融合点", "",
        "| 偏移 | 大小 | 类型 | 字段 |", "|---:|---:|---|---|",
    ]
    for field in spec["fused_point"]["fields"]:
        lines.append(f"| {field['offset']} | {field['size']} | `{field['type']}` | `{field['name']}` |")
    lines += [
        "", "融合点坐标是实际反馈插值得到的 Q13 角度；`A2/A1` 由上位机计算，不在 FPGA 内做除法。",
        "", "## 分片", "",
        "超过传输通道单帧上限的数据必须分片。分片 payload 前 8 字节依次为 `total_length:u32`、`fragment_index:u16`、`fragment_count:u16`。",
        "首片/末片分别设置 `FIRST_FRAGMENT` / `LAST_FRAGMENT`，仍有后续片时设置 `MORE_FRAGMENTS`。",
        "", "## 固定测试帧", "",
        "权威测试向量位于 `Shared/test_vectors/protocol_vectors.json`，Qt 与 FPGA 测试共同使用。",
        "",
    ]
    return "\n".join(lines)


def markdown_registers(spec: dict) -> str:
    lines = [
        "# 寄存器表",
        "",
        "> 本文档由 `Shared/register_map.yaml` 自动生成；请勿直接修改。",
        "",
        "所有寄存器为 32 位、字节寻址、小端。`shadow` 参数先写临时区，验证通过后在安全边界整体生效。",
        "",
        "| 地址 | 名称 | 属性 | 默认值 | 范围/说明 |",
        "|---:|---|---|---:|---|",
    ]
    for reg in spec["registers"]:
        detail = reg.get("description", "")
        if "min" in reg or "max" in reg:
            detail = f"{detail} [{reg.get('min', '-')}, {reg.get('max', '-')} ]".strip()
        lines.append(
            f"| `0x{reg['address']:04X}` | `{reg['name']}` | `{reg['access']}` | "
            f"`0x{reg['reset'] & 0xFFFFFFFF:08X}` | {detail} |"
        )
    lines.append("")
    return "\n".join(lines)


def build_vectors(spec: dict) -> tuple[str, dict[str, bytes]]:
    msg = spec["message_types"]
    flags = 1 << spec["flags"]["ACK_REQUIRED"]
    host = spec["addresses"]["host"]
    fpga = spec["addresses"]["fpga"]

    hello = encode_frame(spec, dst=fpga, src=host, message_type=msg["HELLO"],
                         flags=flags, sequence=0x1234)
    write_payload = struct.pack("<II", 0x00000110, 5000)
    write_reg = encode_frame(spec, dst=fpga, src=host, message_type=msg["WRITE_REG"],
                             flags=flags, sequence=0x1235, payload=write_payload)
    fused_payload = struct.pack(
        "<QIHHhhiiiiIIHH",
        0x0123456789ABCDEF, 7, 3, 42, -8192, 12288,
        -100000, 200000, -300000, 400000, 500000, 600000, 0x00F9, 9
    )
    fused = encode_frame(spec, dst=host, src=fpga, message_type=msg["FUSED_POINT"],
                         flags=1 << spec["flags"]["DATA_VALID"], sequence=0xBEEF,
                         payload=fused_payload)
    bad_crc = bytearray(hello)
    bad_crc[-1] ^= 0x01
    vectors = [
        {"name": "hello_request", "valid": True, "frame_hex": hello.hex(" ").upper()},
        {"name": "write_register_request", "valid": True, "frame_hex": write_reg.hex(" ").upper()},
        {"name": "fused_point_stream", "valid": True, "frame_hex": fused.hex(" ").upper()},
        {"name": "hello_bad_crc", "valid": False, "frame_hex": bytes(bad_crc).hex(" ").upper()},
    ]
    document = json.dumps({"schema_version": 1, "vectors": vectors}, indent=2, ensure_ascii=False) + "\n"
    return document, {
        "hello_request.mem": hello,
        "write_register_request.mem": write_reg,
        "fused_point_stream.mem": fused,
    }


def render_verilog_vectors(memory_vectors: dict[str, bytes]) -> str:
    names = {
        "hello_request.mem": "hello_bytes",
        "write_register_request.mem": "write_bytes",
        "fused_point_stream.mem": "fused_bytes",
    }
    lines = [
        "// Generated by Tools/protocol_generator/generate.py. Do not edit.",
        "task load_fixed_vectors;",
        "    begin",
    ]
    for file_name, data in memory_vectors.items():
        array_name = names[file_name]
        for index, value in enumerate(data):
            lines.append(f"        {array_name}[{index}] = 8'h{value:02X};")
    lines += ["    end", "endtask", ""]
    return "\n".join(lines)


@dataclass(frozen=True)
class Output:
    path: pathlib.Path
    content: str


def expected_outputs(protocol: dict, register_map: dict) -> list[Output]:
    vector_json, memory_vectors = build_vectors(protocol)
    outputs = [
        Output(ROOT / "QT/src/protocol/generated_protocol.h", render_cpp_protocol(protocol)),
        Output(ROOT / "QT/src/protocol/generated_registers.h", render_cpp_registers(register_map)),
        Output(ROOT / "FPGA/rtl/protocol/protocol_defs.vh", render_verilog(protocol, register_map)),
        Output(ROOT / "Docs/通信协议.md", markdown_protocol(protocol)),
        Output(ROOT / "Docs/寄存器表.md", markdown_registers(register_map)),
        Output(ROOT / "Shared/test_vectors/protocol_vectors.json", vector_json),
        Output(ROOT / "FPGA/sim/generated_protocol_vectors.vh", render_verilog_vectors(memory_vectors)),
    ]
    for name, content in memory_vectors.items():
        outputs.append(Output(ROOT / "Shared/test_vectors" / name, "\n".join(f"{x:02X}" for x in content) + "\n"))
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args(argv)

    protocol = load_definition(PROTOCOL_PATH)
    register_map = load_definition(REGISTER_PATH)
    validate(protocol, register_map)
    outputs = expected_outputs(protocol, register_map)
    stale: list[pathlib.Path] = []
    for output in outputs:
        if args.check:
            if not output.path.exists() or output.path.read_text(encoding="utf-8") != output.content:
                stale.append(output.path.relative_to(ROOT))
        else:
            output.path.parent.mkdir(parents=True, exist_ok=True)
            output.path.write_text(output.content, encoding="utf-8", newline="\n")
    if stale:
        print("generated files are stale:", *(f"  {item}" for item in stale), sep="\n", file=sys.stderr)
        return 1
    action = "checked" if args.check else "generated"
    print(f"protocol-generator: {action} {len(outputs)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
